### ISSUE TITLE
Enhancements in Background objects

### ISSUE THREAD

**Issue by Elephant34** [srlearn/srlearn#33]
Line 16: Some parameters that would normally be in the background file might make more sense as classifier parameters. e.g.: maxTreeDepth, nodeSize, numOfClauses

Line 20: - precomputes
- bridgers
- useStdLogicVariables
- usePrologVariables
- okIfUnknown
- range

**Comment by hayesall** [comment]
Related to Issue #23 , some object parameters would make more sense in either estimators or the background, but not both.
